version: '3.8'

services:
  backend:
    container_name: fast_api
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Docker/frontend/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
