FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock /app/

RUN pip install --no-cache-dir poetry=="1.5.0"

RUN poetry install --only frontend

COPY . /app

EXPOSE 8501



# ENTRYPOINT ["poetry", "run", "streamlit", "run", "frontend/tone_app.py", "--server.port=8501", "--server.address=0.0.0.0"]